### ISSUE TITLE
Request: add connection retry timer

### ISSUE THREAD

**Issue by sampie777** [SAHorowitz/MSFS2020-PilotPathRecorder#10]
Hello, thanks for this simple but solid tool. I like it a lot. 

Could you please implement a connection retry timer so that I can just start this program and leave it to be while my flight simulator is starting? That way I don't need to switch programs (which I often forgot which results in no tracking...). 
The timeout doesn't need to be like 1 second, as the simulator takes a couple of minutes to start. So 5 - 30 seconds might be ideal? Anyway, your call!

Thanks in advance, I would appreciate it a lot!

**Comment by SAHorowitz** [comment]
Hello.  Glad you are enjoying the application.  I actually had this function already done but I haven't released the application for a while.  If you don't mind running a test version of the application I can release it to everyone.  The version is 1.4.0A and contains the following changes:

1. Automatic connect and reconnect to Flight Simulator -- tries to connect every 5 seconds
2. Support for multiple delete and multiple Export KML.  Just do a multi-select in the flight list before choosing the function.
3. Added option to open directory after Export KML
4. Fixed crash for invalid waypoints causing a program crash.  Seems that MSFS2020 occasionally has garbage for waypoint names.  The application now handles those and changes the name to "Unknown Waypoint"
5. Fixed crash for airplane names with invalid filename characters

The version can be downloaded from this link - https://drive.google.com/file/d/1W703iOAQm-orbsn7SyRVFFeVxdmWsh9C/view?usp=sharing

Unzip the file over the existing PilotPathRecorder.  Once started click no when it asks you to download a newer version.

Let me know how it works for you.   I will release it to all in a few days unless problems are found.

Thanks.
Steve

**Comment by sampie777** [comment]
Awesome, I will check it out!
