### ISSUE TITLE
Error when running application from another directory

### ISSUE THREAD

**Issue by sampie777** [SAHorowitz/MSFS2020-PilotPathRecorder#17]
Hi there, thanks for the new update with its nice features!

However, since the new update I get an error when running the application through a PowerShell script.

**Reproduction steps**
I use a PowerShell script to start PilotPathRecorder. The script is located in another folder (/Documents instead of /Documents/PilotPathRecorder). The script basically consist of this command:
```
start "C:\Users\myusername\Documents\PilotPathRecorder\FS2020PlanePath.exe"
```

**Expected result**
I expect this command to work outside the PilotPathRecorder directory, as before the update,. without giving any errors. 

**Result**
When I use this command inside the PilotPathRecorder folder, it does work as expected. 
When I use this command outside the PilotPathRecorder folder, it does not work as expected.:

The application starts with an error popup. The error popup doesn't tells me anything specific. Only to look in the log file and that the application will end. 

The logfile _PilotPathRecorderLog.txt_*:
```
=============Error Logging ===========
===========Start============= 17/08/2021 21:53:16
Version: 1.4.0
Additional Information: Error finding or parsing AirportListvx.csv where x is a number.  Please ensure file is in directory and try again
Error Message: Sequence contains no elements
Stack Trace:    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at FS2020PlanePath.MainPage.MainPage_Shown(Object sender, EventArgs e)
===========End=============
```

In my PilotPathRecorder, no _AirportListvx.csv _ is present, but I assume _vx_ is a variable for _v1_, as _AirportListv1.csv_ IS present.

Copying _AirportListv1.csv_ to my command execution directory (/Documents), the command does work and PilotPathRecorder runs without errors. But this is no solid solution for me. 

I suspect the problem might be a faulty relative path in the code?

**Comment by SAHorowitz** [comment]
Hello.  Put the following command before executing the exe

Set-Location -Path C:\Users\myusername\Documents\PilotPathRecorder

That should fix it.

**Comment by SAHorowitz** [comment]
Let me know if this resolved the problem so I can close the issue.

Thanks.
Steve

**Comment by sampie777** [comment]
Hi, unfortunately I didn't have time to check this. I'm quite busy at the moment. But I believe it will work, as it's just setting the path for the command. No problem. Just thought to let you know about what appears to be a relative path error in the code (I should expect the executable to use its own path). But no worries! ;)

**Comment by SAHorowitz** [comment]
Thanks for letting me know. If you run into issues on this again, just let me know. Hopefully you have time to sim fly again soon.
